# Default environmnet
email:
  domain:
    validate:
      api:
        endPoint: https://emailvalidation.abstractapi.com/v1/
        key: api_key
        value: 0c04c1fd43394483b4d370feba5cedc6
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
server:
  port: 8081
NotEmpty:
  customer:
    firstName: First name must be provided
---
# dev environment configurations
spring:
  profiles: dev
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER_NAME:root}
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:shopifyme-customers}
    password: ${DB_USER_PASSWORD:bhim}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true
---
# qa environment configurations
spring:
  profiles: qa
  h2:
    console:
      enabled: true
      path: /h2Console
 
